### ISSUE TITLE
Make TMulticastEvent parallel using TTask.Run

### ISSUE THREAD

**Issue by CBertrand2** [grijjy/JustAddCode#13]
Would it be possible to add an option to ``TMulticastEvent`` so it would call handlers in parallel instead of being stuck by them ?
The second benefit would be that handlers would run in parallel as well in place of being queued. So they don't delay and slow down one another.

In ``TMulticastEvent.Invoke``, the ``FData.Count`` loop may use ``TTask.Run`` in place of simple calls.

**Comment by erikvanbilsen** [comment]
This is just a sample implementation. You can modify it yourself however you want.
For me, the main goal was to create a very efficient implementation (in both memory and runtime cost), and using tasks to run event handlers would negate that a bit (especially if the event handlers don't have much code). Also, events are used a lot in GUI apps, and firing events from secondary threads could require the handlers to synchronize with the main thread, adding more complexity and performance issues.

But please feel free to make any modifications to the code you want. The license permits you to do anything with it😉

**Comment by CBertrand2** [comment]
I understand your point of view.
Thank you for you answer. And for your source code, by the way.
