### ISSUE TITLE
Android + Berlin

### ISSUE THREAD

**Issue by robert-b-idus** [grijjy/JustAddCode#2]
Got strange linking problems which at a glance looked like they were coming from libmidas.a. 

When looking further and changing from msbuild mode to compiling from IDE i saw references regarding __cxa_demangle which got me to think libgnustl_static wasn't linked. 

When i added -lgnustl_static to the linker flags in delphi it compiled.

**Comment by robert-b-idus** [comment]
Oh sorry, I included the grijjy-error reporting/stack trace sample in an existing app.

The libmidas.a error was not related to the actual problem, which is why it took me a while to find.

This issue was more meant as information. -lgnustl_static was needed to make the linker do its job.

**Comment by neslib** [comment]
That' strange, since in Grijjy.ErrorReporting.pas, libgnustl_static.a is linked explicitly with the cxa_demangle function. Is this issue only when using MSBuild, or does it also occur when building from the IDE?

**Comment by robert-b-idus** [comment]
This is what the linker says without -lgnustl_static

[DCC Error] E2597 c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:function DllGetClassObject: error: undefined reference to 'operator delete(void*)'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:function DllGetClassObject: error: undefined reference to 'operator delete(void*)'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:function DllGetClassObject: error: undefined reference to 'operator delete(void*)'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:function DllGetClassObject: error: undefined reference to 'operator delete(void*)'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o)(.ARM.extab.text.DllGetClassObject+0x0): error: undefined reference to '__gxx_personality_v0'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o)(.ARM.extab.text._ZN14DSBASE_Factory14CreateInstanceEP8IUnknownRK4GUIDPPv+0x0): error: undefined reference to '__gxx_personality_v0'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o)(.ARM.extab.text._ZN16DSCursor_Factory14CreateInstanceEP8IUnknownRK4GUIDPPv+0x0): error: undefined reference to '__gxx_personality_v0'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o)(.ARM.extab.text._ZN8TAlchemy6MakeDSEPP7TDSBASE+0x0): error: undefined reference to '__gxx_personality_v0'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:vtable for DS_Factory: error: undefined reference to '__cxa_pure_virtual'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:vtable for DS_Factory: error: undefined reference to '__cxa_pure_virtual'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:typeinfo for DS_Factory: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
  E:\Backups\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:typeinfo for DSBASE_Factory: error: undefined reference to 'vtable for __cxxabiv1::__vmi_class_type_info'
  E:\Backups\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:typeinfo for DSCursor_Factory: error: undefined reference to 'vtable for __cxxabiv1::__vmi_class_type_info'
  E:\Backups\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:typeinfo for DATAPACKETREAD_Factory: error: undefined reference to 'vtable for __cxxabiv1::__vmi_class_type_info'
  E:\Backups\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:typeinfo for DATAPACKETWRITE_Factory: error: undefined reference to 'vtable for __cxxabiv1::__vmi_class_type_info'
  E:\Backups\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:typeinfo for TAlchemy: error: undefined reference to 'vtable for __cxxabiv1::__class_type_info'
  E:\Backups\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:typeinfo for IUnknown: error: undefined reference to 'vtable for __cxxabiv1::__class_type_info'
  E:\Backups\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:typeinfo for IClassFactory: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
  E:\Backups\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:vtable for IClassFactory: error: undefined reference to '__cxa_pure_virtual'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(alchemy.o):C:\Builds\tp\runtime\data\dsnap\midas\alchemy.cpp:vtable for IClassFactory: error: undefined reference to '__cxa_pure_virtual'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(curinit.o):C:\Builds\tp\runtime\data\dsnap\midas\curinit.cpp:function DSCursor::~DSCursor(): error: undefined reference to 'operator delete[](void*)'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(curinit.o):C:\Builds\tp\runtime\data\dsnap\midas\curinit.cpp:function DSCursor::~DSCursor(): error: undefined reference to 'operator delete[](void*)'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(curinit.o):C:\Builds\tp\runtime\data\dsnap\midas\curinit.cpp:function DSCursor::~DSCursor(): error: undefined reference to 'operator delete[](void*)'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(curinit.o):C:\Builds\tp\runtime\data\dsnap\midas\curinit.cpp:function DSCursor::~DSCursor(): error: undefined reference to 'operator delete[](void*)'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(curinit.o):C:\Builds\tp\runtime\data\dsnap\midas\curinit.cpp:function __clang_call_terminate: error: undefined reference to '__cxa_begin_catch'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(curinit.o):C:\Builds\tp\runtime\data\dsnap\midas\curinit.cpp:function __clang_call_terminate: error: undefined reference to 'std::terminate()'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(curinit.o):C:\Builds\tp\runtime\data\dsnap\midas\curinit.cpp:typeinfo for TDSCursor: error: undefined reference to 'vtable for __cxxabiv1::__class_type_info'
  E:\Backups\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(ds.o):C:\Builds\tp\runtime\data\dsnap\midas\ds.cpp:function LTABLEList::~LTABLEList(): error: undefined reference to 'std::terminate()'
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(ds.o):C:\Builds\tp\runtime\data\dsnap\midas\ds.cpp:typeinfo for VARList: error: undefined reference to 'vtable for __cxxabiv1::__class_type_info'
  E:\Backups\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(ds.o):C:\Builds\tp\runtime\data\dsnap\midas\ds.cpp:typeinfo for LTABLEList: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
  E:\Backups\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(ds.o):C:\Builds\tp\runtime\data\dsnap\midas\ds.cpp:typeinfo for VARStrList: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
  E:\Backups\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  c:\\program files (x86)\\embarcadero\\studio\\18.0\\lib\\Android\\Release/libmidas.a(idxfilt.o):C:\Builds\tp\runtime\data\dsnap\midas\idxfilt.cpp:function DSIDXFILT::~DSIDXFILT(): error: undefined reference to 'std::terminate()'

**Comment by neslib** [comment]
Thanks for the log. Very strange indeed. I cannot reproduce this when using the Error Reporting code (with or without using Datasnap or Midas). At least you have a solution for this issue by adding the linker flag.
