### ISSUE TITLE
All comunity whould like error reporter for windows too. Eureka and MadExcept not are free and open source

### ISSUE THREAD

**Issue by marcosbarreto** [grijjy/JustAddCode#6]

**Comment by erikvanbilsen** [comment]
EurekaLog and madExcept are excellent error reporting tools and well worth the money.

At Grijjy, we use EurekaLog for our Windows apps, and are very happy with it. So for us, there is no reason to build a (free and open source) competitor.

The goal of our error reporting building blocks is to support non-Windows platforms. And remember, these are "just" building blocks and not a complete solution.
